contentType: chart
version: 1
name: "Hospital Rating by Ownership"
slug: hospital-rating-by-ownership
spaceSlug: hospital-management
tableName: hospitals
metricQuery:
  exploreName: hospitals
  dimensions:
    - hospitals_hospital_ownership
  metrics:
    - hospitals_avg_hospital_overall_rating
  tableCalculations: []
  filters: {}
  sorts:
    - fieldId: hospitals_avg_hospital_overall_rating
      descending: true
  limit: 500
chartConfig:
  type: cartesian
  config:
    layout:
      xField: hospitals_hospital_ownership
      yField:
        - hospitals_avg_hospital_overall_rating
    eChartsConfig:
      series:
        - type: bar
          encode:
            xRef:
              field: hospitals_hospital_ownership
            yRef:
              field: hospitals_avg_hospital_overall_rating
          label:
            show: true
            position: "top"
      xAxis:
        - name: "Ownership Type"
      yAxis:
        - name: "Average Rating (1-5)"
