contentType: chart
version: 1
name: "Total Services (Outpatient)"
slug: total-services-outpatient
spaceSlug: hospital-management
tableName: outpatient_charges
metricQuery:
  exploreName: outpatient_charges
  metrics:
    - outpatient_charges_sum_number_services
  dimensions: []
  tableCalculations: []
  filters: {}
  sorts: []
  limit: 500
chartConfig:
  type: big_number
  config:
    label: "Total Services"
    showUnit: false
