contentType: chart
version: 1
name: "Outpatient Services Trend"
slug: outpatient-services-trend
spaceSlug: hospital-management
tableName: outpatient_charges
metricQuery:
  exploreName: outpatient_charges
  dimensions:
    - outpatient_charges_service_year_year
  metrics:
    - outpatient_charges_sum_number_services
  tableCalculations: []
  filters: {}
  sorts:
    - fieldId: outpatient_charges_service_year_year
      descending: false
  limit: 500
chartConfig:
  type: cartesian
  config:
    layout:
      xField: outpatient_charges_service_year_year
      yField:
        - outpatient_charges_sum_number_services
    eChartsConfig:
      series:
        - type: line
          encode:
            xRef:
              field: outpatient_charges_service_year_year
            yRef:
              field: outpatient_charges_sum_number_services
          label:
            show: true
            position: "top"
      xAxis:
        - name: "Year"
      yAxis:
        - name: "Total Services"
